# Generated by Django 4.1 on 2022-08-05 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("new_digs_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("primary_breed", models.CharField(max_length=50, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="new_digs_app.owner",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="person",
            name="last_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.DeleteModel(
            name="Pet",
        ),
        migrations.AddConstraint(
            model_name="dog",
            constraint=models.CheckConstraint(
                check=models.Q(("primary_breed__in", ["Beagle", "Border Collie"])),
                name="dog_primary_breed_check",
            ),
        ),
    ]
